// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEwDlzs7zvGtcyNLpXeNVrzoPwUr7wSkA',
    appId: '1:676323475057:web:fc7dec01e3ad5dcf88a5d0',
    messagingSenderId: '676323475057',
    projectId: 'metasoft-iot-2601-17157',
    authDomain: 'metasoft-iot-2601-17157.firebaseapp.com',
    storageBucket: 'metasoft-iot-2601-17157.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlzt3CVcsb6D9r2bnWFLybgYO7k2DccVk',
    appId: '1:676323475057:android:e840d889916c618888a5d0',
    messagingSenderId: '676323475057',
    projectId: 'metasoft-iot-2601-17157',
    storageBucket: 'metasoft-iot-2601-17157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCphU5KgXeIZ9t2voC2NwJGcfkr4SX2LU0',
    appId: '1:676323475057:ios:1cc2151dcf2dfcc188a5d0',
    messagingSenderId: '676323475057',
    projectId: 'metasoft-iot-2601-17157',
    storageBucket: 'metasoft-iot-2601-17157.firebasestorage.app',
    iosBundleId: 'com.example.veyraMobileApp',
  );
}
